### ISSUE TITLE
Linux missing user directory [BUG] 

### ISSUE THREAD

**Issue by ryanfantus** [Apple-Music-Electron/Apple-Music-Electron#188]
**Describe the bug**
A fresh installation of 2.5.0 failed to create a user directory which flagged as an ENOENT error message upon launching the program.

**To Reproduce**
1. Remove `~/.cache/Apple Music` directory
2. Remove apple-music-electron application
3. Install 2.5.0 of apple-music-electron
4. Launch application
5. Receive error message about missing `~/.cache/Apple Music/Themes` directory

**Expected behavior**
Themes directory auto-generated when cache directory is first made, and there is no complaint

**Screenshots**

**Desktop (please complete the following information):**
 - OS: up-to-date arch linux 64 bit
 - Application Version 2.5.0

**Log File**
Check your log file for any errors or the last message to be sent and post them here.

**Additional context**

**Have you followed the troubleshooting guide found [here](https://github.com/Apple-Music-Electron/Apple-Music-Electron/wiki/Troubleshooting) and checked for any outstanding/pinned issues that can help?**
Yes

**Comment by coredev-uk** [comment]
For the time being, what I suggest you do is use your file manager and edit the permissions of `.cache/Apple Music/themes` and change it to have all permissions for the user. For some reason, fs.chmod acts weirdly on Linux as this issue is not experienced on Windows, and the copySync function that we use to copy the themes folder to the local directory doesn't always give the correct permissions. I'll pin this issue and lock this issue for the time being, if I have any updates on fixing this I'll let you know.
